- name: Run database container
  docker_container:
    name: database
    image: elisadty/tp-devops-database
    env:
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    networks:
      - name: my-network
    restart_policy: always
    state: started
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python