
- name: Run HTTP proxy container
  docker_container:
    name: httpd
    image: elisadty/tp-devops-httpd
    ports:
      - "80:80"
    networks:
      - name: my-network
    restart_policy: always
    state: started
    pull: yes

  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
