
# tasks file for roles/launch_app

- name: Run Spring Boot API container
  docker_container:
    name: simple-api
    image: elisadty/tp-devops-simple-api
    pull: yes

    env:
      DATABASE_HOST: database
      DATABASE_PASSWORD: pwd
    ports:
      - "8082:8080"
    networks:
      - name: my-network
    restart_policy: always
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python