---
# - name: Deploy full application
#   hosts: all
#   become: true

- hosts: all
  become: true
  gather_facts: true

  roles:
    - docker
    - network
    - database
    - launch_app
    - launch_proxy

